### ISSUE TITLE
Error while executing code

### ISSUE THREAD

**Issue by johnfriend** [DPLYR-dev/SplashScreenFlutterPackage#50]
Please find below the error message that I have received when I used the example file 

**Invalid argument(s): widget.routeName must be a String beginning with forward slash (/)**

The relevant error-causing widget was: 
  LeviSplash file:///Users/******/Desktop/Flutter/*****/lib/main.dart:7:13
When the exception was thrown, this was the stack: 
#0      _SplashScreenState.initState (package:splashscreen/splashscreen.dart:86:7)
#1      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
#2      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
#3      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#4      Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)

What should i do ?

____

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Drifeter** [comment]
I'm having the same problem, even with a new project:
#1 create a new flutter project
#2 update pubscec.yaml dependencies => splashscreen: ^1.3.3
#3 copy the example from the first page into main.dart:
`import 'package:flutter/material.dart';
import 'package:splashscreen/splashscreen.dart';

void main() {
  runApp(new MaterialApp(
    home: new MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return new SplashScreen(
        seconds: 14,
        navigateAfterSeconds: new AfterSplash(),
        title: new Text(
          'Welcome In SplashScreen',
          style: new TextStyle(fontWeight: FontWeight.bold, fontSize: 20.0),
        ),
        image: new Image.network('https://i.imgur.com/TyCSG9A.png'),
        backgroundColor: Colors.white,
        styleTextUnderTheLoader: new TextStyle(),
        photoSize: 100.0,
        onClick: () => print("Flutter Egypt"),
        loaderColor: Colors.red);
  }
}

class AfterSplash extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
          title: new Text("Welcome In SplashScreen Package"),
          automaticallyImplyLeading: false),
      body: new Center(
        child: new Text(
          "Done!",
          style: new TextStyle(fontWeight: FontWeight.bold, fontSize: 30.0),
        ),
      ),
    );
  }
}
`
#4 Run Flutter and get the error:

════════ Exception caught by widgets library ═══════════════════════════════════
The following ArgumentError was thrown building MyApp(state: _MyAppState#1b99e):
Invalid argument(s): widget.routeName must be a String beginning with forward slash (/)

The relevant error-causing widget was
MyApp
lib\main.dart:6
When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
packages/splashscreen/splashscreen.dart 87:80                                                                              initState
packages/flutter/src/widgets/framework.dart 4812:57                                                                        [_firstBuild]
packages/flutter/src/widgets/framework.dart 4649:5                                                                         mount
packages/flutter/src/widgets/framework.dart 3615:13                                                                        inflateWidget
...
════════════════════════════════════════════════════════════════════════════════

**Comment by KarimMohamed20** [comment]
Thanks for this report, I will check it and push a new version soon.

**Comment by hons82** [comment]
The if statement at line 83 should probably look something like this

`    if (widget.routeName != null && widget.routeName is String && "${widget.routeName[0]}" != "/")
      throw new ArgumentError("widget.routeName must be a String beginning with forward slash (/)");
`

**Comment by Drifeter** [comment]
> 
> 
> The if statement at line 83 should probably look something like this
> 
> ` if (widget.routeName != null && widget.routeName is String && "${widget.routeName[0]}" != "/") throw new ArgumentError("widget.routeName must be a String beginning with forward slash (/)");`

Thanks, for me solved the issue 👍
