### ISSUE TITLE
Invalid argument(s): widget.routeName must be a String beginning with forward slash (/)

### ISSUE THREAD

**Issue by Nkurayijahubert** [DPLYR-dev/SplashScreenFlutterPackage#52]
It has been working well but after the update you made, it is giving an error.

Here is my code

class WelcomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'WKS',
      home: Scaffold(
        backgroundColor: kAccentLight,
        body: SafeArea(
          child: SplashScreen(
            seconds: 4,
            navigateAfterSeconds: App(),
            title: new Text('Title',
              style: TextStyle(fontSize: 36,
                  color: kAmber400,
                  fontWeight: FontWeight.bold),
            ),
            backgroundColor: kAccent,
            styleTextUnderTheLoader: new TextStyle(),
            loaderColor: kBrown900,
          ),
        ),
      )
    );
  }
}

**Comment by ImTung** [comment]
Same here

**Comment by edukmattos** [comment]
Insert the parameter routeName


`SplashScreen(
          seconds: 2,
          **routeName: "/",**
          onClick: () => print("Flutter Egypt"),
          title: Text(
            'Welcome In SplashScreen',
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20.0),
          ),
          navigateAfterSeconds: WellcomePage,
          loaderColor: Colors.transparent,
        ),`

**Comment by ImTung** [comment]
@Nkurayijahubert just waiting author pub new version or follow this file merged [#51](https://github.com/DPLYR-dev/SplashScreenFlutterPackage/pull/51/files) to temporarily running

**Comment by marceloreis13** [comment]
I'm facing the same thing here

**Comment by Akiat** [comment]
The same here. The fix with routeName works perfectly but it will be great to push the #51 in a new version 👍

**Comment by KarimMohamed20** [comment]
Sorry for being late, Currently there is a new version at pub.dev without this issue.
