### ISSUE TITLE
Null-Safety support

### ISSUE THREAD

**Issue by kuromukira** [DPLYR-dev/SplashScreenFlutterPackage#63]
**Is your feature request related to a problem? Please describe.**
No dart null-safety support which prevents us from migrating to null-safety

**Describe the solution you'd like**
Add dart null-safety support

**Describe alternatives you've considered**
Copy your code and implement null-safety inside our project

**Additional context**
NA

**Comment by leynier** [comment]
Any update guys? I could be make a PR with null safety support implementation.

**Comment by ahmedmgh67** [comment]
Hello @kuromukira , Adding null-safety support is on our roadmap, if @leynier can make a PR first we'll merge it for sure and we would love that you contribute to the project, otherwise it's still gonna be developed in the coming 2-3 months

**Comment by leynier** [comment]
PR is comming 🚀 😄 

> Hello @kuromukira , Adding null-safety support is on our roadmap, if @leynier can make a PR first we'll merge it for sure and we would love that you contribute to the project, otherwise it's still gonna be developed in the coming 2-3 months

**Comment by kuromukira** [comment]
Thanks @leynier 👌🏻

@ahmedmgh67 Thanks. I'd check the issues whenever I get free time to see if I'll be able to contribute on some of them!

**Comment by leynier** [comment]
PR is done 🚀

**Comment by ahmedmgh67** [comment]
@leynier Amazing!, I'll review it now, merge it, and publish it as a minor update

**Comment by JoynerPerez1987** [comment]
Please, aprobe the @leynier PR

**Comment by leynier** [comment]
@ahmedmgh67 please 🙏🏻 review this PR #64, we need null safety support.
