### ISSUE TITLE
Splash Screen is not supported with nullsafety

### ISSUE THREAD

**Issue by Ankit-jailwal** [DPLYR-dev/SplashScreenFlutterPackage#70]
When I am trying to implement splash screen in my code with null safety. Then it shows - package: splashscreen is not supported with null safety.
Flutter version: 2.2.0
Framework • revision b22742018b 
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
![splash scree](https://user-images.githubusercontent.com/55527244/120016273-06b62500-c002-11eb-9dd4-9279036d4a46.PNG)

**Comment by brunomaffei** [comment]
I'm getting the same problem.....nobody have the solution?

**Comment by Ankit-jailwal** [comment]
You can solve this problem by adding this in your pubspec.yaml file.
splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master

**Comment by brunomaffei** [comment]
But i've to remove the dependecy?

![image](https://user-images.githubusercontent.com/47982525/120899178-bf80f300-c604-11eb-8027-5b1dbfb0e0f2.png)

**Comment by Ankit-jailwal** [comment]
Can you show me your complete code?

**Comment by brunomaffei** [comment]
I've to downgrade the version =/ to work....so any suggestion?
![image](https://user-images.githubusercontent.com/47982525/120912406-2fbf6100-c665-11eb-966d-72673769f5ab.png)

**Comment by calvintam236** [comment]
duplicate of #65

**Comment by Ankit-jailwal** [comment]
I think the solution is available at #65, so I am closing this issue.
